# This is a basic workflow to help you get started with Actions

name: create cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      # - name: cluster info
      #   run: |
      #     kubectl cluster-info
      #     kubectl get pods -n kube-system
      #     echo "current-context:" $(kubectl config current-context)
      #     echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: install argocd
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          sleep 40
          kubectl get nodes -o wide
          kubectl get nodes -o jsonpath={.items[0].status.addresses[0].address}
          kubectl get pods -n argocd
          ip a
          kubectl get svc -n argocd
      - name: install argocd-cli
        run: |
          VERSION=v2.2.5; curl -sL -o argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
      - name: argocd login
        run: |
          export password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d);
          echo $password
          export argocd_svc=$(kubectl get svc -n argocd argocd-server -o jsonpath={.spec.clusterIP})
          echo $argocd_svc
          argocd login $argocd_svc --username=admin --password=$password
          argocd app list
      - name: argocd resource install
        run: |
          kubectl apply -f application/app_of_apps/.
          kubectl get app -A
      - name: Test1
        run: exit 1
      - name: Test2
        run: exit 1
      - name: Test3
        run: exit 0
        

        



